apiVersion: v2
name: paperless
description: Helm chart for Paperless-ngx with optional PostgreSQL and Redis
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: postgresql
    version: "15.5.18"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "19.6.2"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
