apiVersion: v2
name: paperless
description: Helm chart for Paperless-ngx with optional PostgreSQL and Redis
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: postgresql
    version: "18.1.10"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "23.2.12"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
