apiVersion: v2
name: external-secrets
description: Helm chart for external-secrets-operator
type: application
version: 1.0.0
appVersion: "latest"

dependencies:
  - name: external-secrets
    version: 1.1.0
    repository: https://charts.external-secrets.io/


