{{- if and .Values.gotenberg .Values.gotenberg.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotenberg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotenberg
  template:
    metadata:
      labels:
        app: gotenberg
    spec:
      containers:
        - name: gotenberg
          image: {{ .Values.gotenberg.image }}:{{ .Values.gotenberg.tag }}
          args:
            - "gotenberg"
            - "--chromium-disable-javascript=true"
            - "--chromium-allow-list=file:///tmp/.*"
          ports:
            - containerPort: {{ .Values.gotenberg.containerPort }}
          resources:
            requests:
              cpu: "0.5"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: gotenberg
spec:
  selector:
    app: gotenberg
  ports:
    - port: {{ .Values.gotenberg.servicePort }}
      targetPort: {{ .Values.gotenberg.containerPort }}
{{- end }}
