{{- if .Values.database.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
type: Opaque
stringData:
  username: {{ default "paperless" .Values.database.username | quote }}
  database: {{ default "paperless" .Values.database.database | quote }}
  password: {{ default (randAlphaNum 32) .Values.database.password | quote }}
  postgres-password: {{ default (randAlphaNum 32) .Values.database.postgresPassword | quote }}
{{- end }}
