{{- if and .Values.postgresql .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.secretName }}
type: Opaque
stringData:
  username: {{ default "paperless" .Values.postgresql.auth.username | quote }}
  database: {{ default "paperless" .Values.postgresql.auth.database | quote }}
  password: {{ (randAlphaNum 32) | quote }}
  postgres-password: {{ (randAlphaNum 32) | quote }}
{{- end }}
