{{- if and .Values.tika .Values.tika.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      labels:
        app: tika
    spec:
      containers:
        - name: tika
          image: {{ .Values.tika.image }}
          ports:
            - containerPort: {{ .Values.tika.containerPort }}
          resources:
            requests:
              cpu: "0.5"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: tika
spec:
  selector:
    app: tika
  ports:
    - port: {{ .Values.tika.servicePort }}
      targetPort: {{ .Values.tika.containerPort }}
{{- end }}
