apiVersion: v2
name: argocd
description: Helm chart for argocd
type: application
version: 1.0.0
appVersion: "latest"

dependencies:
  - name: argo-cd
    version: 9.1.4
    repository: https://argoproj.github.io/argo-helm