apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-paperless-sealed-secrets
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/abeguin/argocd.git
        revision: main
        directories:
          - path: apps/paperless/*
          - path: apps/paperless/templates
            exclude: true

  template:
    metadata:
      name: 'paperless-sealed-secrets-{{ index (splitList "/" .path.path) 2 }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/abeguin/argocd.git
        targetRevision: main
        path: '{{ .path.path }}'        # apps/paperless/abe  => appliquera paperless-db-secret-sealed.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: 'paperless-{{ index (splitList "/" .path.path) 2 }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true