apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applicationsets-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abeguin/argocd.git
    targetRevision: main
    path: argocd                 # chemin du dossier contenant apps-smart.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
