apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: "cert-manager-repository"
  type: "helm"
  url: "https://charts.jetstack.io"